theme: jekyll-theme-architect
title: [Afghan Dictionary - دیکشنری افغان]
description: [dictionary for dari, english , and pashto]
show_downloads: ["https://github.com/rahmanrezaee/afghan_dic/edit/gh-pages/_config.yml]
