theme: jekyll-theme-architect
title: [Afghan Dictionary - دیکشنری افغان]
description: [dictionary for dari, english , and pashto]
github:
  zip_url: http://example.com/download.zip
  another_url: another value
